### ISSUE TITLE
Use timestamp and ts_edited values for inserting/updating backblasts instead of relying on primary key alone

### ISSUE THREAD

**Issue by srschaecher** [F3Nation-Community/PAXminer#14]
Currently, the design is not very smart for inserting/updating backblasts which results in VERY slow performance. The beatdowns table primary key is ao_id + bd_date + q_user_id. So when the script runs, it pulls EVERY message from each AO channel in slack and then only processes those that are less than N days old (as specified in the cutoff_date line 64, default is the past 7 days). It then takes every one of those messages and looks for any that start with "Backblast" or other accepted varieties. From those backblasts, it then parses the information and tries to insert them into the database every time it runs. If there is already a record with that same primary key, then the insert fails and it just moves on. 

This obviously results in a lot of wasted effort, attempting to re-insert every backblast that already exists. What I've been WANTING to do for a long time and just haven't gotten to it is to first pull an array of existing beatdown timestamps and ts_edited (maybe only from the past 14 days or something to keep it small?) and then compare the backblast timestamp and ts_edited to that array. If a backblast timestamp is already on the list and ts_edited is either null or matches the existing ts_edited, then it passes over it. If the timestamp exists but has a new ts_edited value (meaning the backblast was updated), then it will update the entire backblast record. Does that make sense? Open to other approaches... but using the timestamp and ts_edited values should allow us to do two important things:
1) Update backblasts that have been edited
2) Avoid trying to insert backblasts that already exist in the database (instead of blindly trying to push every one and waiting for the database to reject it)

**Comment by evanpetzoldt** [comment]
Nothing to add, this makes perfect sense to me!

When you say "update the entire backblast record"... do you mean a full update? FWIW, in Slackblast when someone uses the edit button, I do a full delete of all records on beatdowns and attendance associated with that timestamp and re-insert. I could instead do an "upsert", but PAX that were deleted from the backblast would remain in the db.

**Comment by farrellw** [comment]
I think an updated slack message ( e.g. beatdown ) results in the following behavior.

Beatdown table:
Updates into the beatdown table.

Beatdown Attendance:
- Deletes based on the timestamp key.
- Inserts into the beatdown table.

**Comment by farrellw** [comment]
I have a good chunk at this locally for review. Do y'all just push up a branch and create an MR.  Or go through the whole separate project / fork MR.  If the former, can someone add me as a contributor.

**Comment by farrellw** [comment]
I have an attempt at this in a local branch for review. Do y'all just push up a branch and create an MR.  Or go through the whole separate project / fork MR.  If the former, can someone add me as a contributor.

cc: @evanpetzoldt , @srschaecher

**Comment by taterhead247** [comment]
This may be crazy. But what if we don't do this. What if, instead, every time some does a paxminer style backblast, we ingest it, then message them that they should install Slackblast? And we keep messaging them until they give in.

**Comment by evanpetzoldt** [comment]
LOL @taterhead247 :D You'd be surprised how many guys still avoid Slackblast like the plague. 

@farrellw I invited you to the organization, not sure if that grants you contributor access to this repo though...

**Comment by farrellw** [comment]
@taterhead247 never heard of Slackblast. I'll take a look but either way this probably needs fixing. I don't think everyone will migrate immediately.

https://github.com/F3Nation-Community/PAXminer/pull/16 is what I wrote up this morning. I'll look back at the merge conflict come Monday, feel free to review.

**Comment by farrellw** [comment]
Merge conflict fixed, #16 ready for review / discussion.

Handles an updated backblast ( in this case a slack message ).

- Treats the slack message timestamp as a unique ID. 
- - Technically, the gauranteed unique id is slack channel + timestamp. But since we used the concept of channels as our AOs. The AO + timestamp unique id doesn't make sense, because the AO can change with an updated backblast. 
- For messages that have already been processed, it compares the timestamp and the ts_edited to determine whether that action should be Ignored or Updated.
- For messages that the ts_edited is the same, those messages are ignored. This will save database calls and reduce the DB errors. We won't be running a bunch of inserts we know are going to fail the uniqueness key.
- For messages that the ts_edited is greater, that message is updated.
- - The backblast table is upserted. ( Because the unique key ( ao + date + q ) doesn't match our unique timestamp idea, we have to do an update rather than mysql normal upsert ( e.g. innsert with on key match logic. )
- - A delete statement runs on the beatdown_attendance table to clear out the previous backblast, and then the inserts are run again. Running the delete rather than the updates should help deal with new PAX and with PAX being listed wrongly and then removed.
- For messages that have not been inserted yet, straight insert.
- Move a bit of the code used into functions.

**Comment by farrellw** [comment]
Done and merged, might need some help deploying to slack. Or does the app in slack just need to be re-updated?

**Comment by evanpetzoldt** [comment]
@farrellw has Beaker (@srschaecher ) reviewed this PR? I'm sure it's good, but I personally have been unable to review or test.

Deployment would just be pulling in the update to Beaker's server that he runs PAXMiner from once that's good to go.

**Comment by farrellw** [comment]
@evanpetzoldt Been working a ( very little ) with Beaker on slack. He mentioned that he'll get to deployment when he's got a second.

**Comment by farrellw** [comment]
This is working after being deployed. I made a very small change to logging, after which I will close this issue. https://github.com/F3Nation-Community/PAXminer/pull/20

Note that updates are handled now through paxminer ( but not deletes yet ).
