### ISSUE TITLE
Adjust beatdown primary key discussion

### ISSUE THREAD

**Issue by farrellw** [F3Nation-Community/PAXminer#21]
While ao + date + q has worked for us very well in the past, I think it has a few limitations. For example, a 24 hour beatdown where one person leads 3 workouts in that same date. In the real world, there is nothing wrong with a person hosting a beatdown on the same date.

I wanted to bring up an idea for discussion. How do y'all feel about adjusting the schema to treat { timestamp + attribute } as the unique identifier for a beatdown?

Beatdowns are currently tied to a single slack messages in paxminer. Does slackbot essentially also equate one post ( done by slackbot ) to one beatdown cc: @evanpetzoldt ? 

These slack messages carry with a timestamp, which is guaranteed to be unique within a slack channel. It is not guaranteed to be unique within a workspace, but has a pretty damn good chance of being unique within a workspace. So we could do { timestamp + workspace } and catch 99.999% of all cases. Once every probably like 100 years we get hit with a duplicate timestamp. Or { timestamp + channel posted + workspace } to catch the uniqueness 100%.

Along with this, I think we can disassociate the channel posted with the ao being used.

As a final idea, this leaves open the possibility that we might one day say the Q is optional, although we don't have to go down that road right away.

**Comment by evanpetzoldt** [comment]
Definitely agree with all of this! @farrellw to answer your question, Slackblast adheres to the primary key that PAXminer has (because it has to currently), but yes it essentially identifies posts and backblasts already.

I agree on using timestamp as a key; one hiccup is that @srschaecher only implemented timestamp in the last year or so, so all data from before that has null timestamps. One thought I had was to use an autogenerated int as the actual primary key, but have timestamp as a unique key constraint to prevent duplication.

**Comment by farrellw** [comment]
For records where the timestamp is null, we can approximate the timestamps by just doing timestamp at start of that bd_date + random integer between 1 and 86000. That way they still make some sense, and then could go forward in the future assuming that is always unique and required.

**Comment by farrellw** [comment]
I think we are in agreement on this @evanpetzoldt . But its stale by now, and probably just going to be rolled into the database migration so I'm closing this issue
