### ISSUE TITLE
Using channel_id instead of AO

### ISSUE THREAD

**Issue by nfaber** [F3Nation-Community/PAXminer#39]
https://github.com/F3Nation-Community/PAXminer/blob/348d4b14bba4b8251fb374244a52a9d4f5f0dc7d/PAX_BD_Miner.py#L438

Should this line refer to the AO instead of the `channel_id`?

**Comment by farrellw** [comment]
@nfaber I was wondering this myself awhile ago. @srschaecher Are backblasts supposed to be routed to the AO in the backblast or the channel it was posted in?

If its the ao in the backblast, I can make that change. It's been this way, the way above, for at least two years:

https://github.com/F3Nation-Community/PAXminer/blame/main/PAX_BD_Miner.py#L438

**Comment by farrellw** [comment]
My guess is that it was switched to channel_id because invalid AOs were being put there? No idea, but here's the behavior I would propose:

1) Takes the AO id if it matches a valid channel
2) Falls back to channel_id if it doesn't match a valid channel?

Or do we just fail it entirely if the AO id doesn't match a valid channel?

**Comment by srschaecher** [comment]
This was under the original assumption that backblasts are posted to the AO channel. I changed it to use channel_id because some AO names were breaking things and we wanted to enforce that BBs were posted to AO channels to facilitate post-beatdown mumblechatter and not to generic “backblast” channels that nobody reads… so this enforced that… however, this was back when only a few regions were using it.

I’m open to changing it if you guys prefer…

From: Will Farrell ***@***.***>
Date: Tuesday, August 27, 2024 at 11:45 AM
To: F3Nation-Community/PAXminer ***@***.***>
Cc: srschaecher ***@***.***>, Mention ***@***.***>
Subject: Re: [F3Nation-Community/PAXminer] Using channel_id instead of AO (Issue #39)

@nfaber<https://github.com/nfaber> I was wondering this myself awhile ago. @srschaecher<https://github.com/srschaecher> Are backblasts supposed to be routed to the AO in the backblast or the channel it was posted in?

If its the ao in the backblast, I can make that change

**Comment by nfaber** [comment]
This all makes sense. We are an offending region that has most of our blasts posted in #mumblechatter. But now that we have Slackblast active, I think people will post in the AO channels. 

I like the solution of looking at the ao field first and then falling back on channel_id if the AO field is bogus or nonexistent.

**Comment by farrellw** [comment]
It sounds like, besides Snowbird @nfaber , other regions post all their backblasts in random channels as well. I think it makes sense to enable people to specify the AO within the backblast ( otherwise I'd advocate getting rid of the AO line entirely, which is also a thought ). Because we have the AO line in there, I think we should allow for an AO to be tagged and stored in the database. 

Here's an MR (  
https://github.com/F3Nation-Community/PAXminer/pull/40 ) that adjusts the behavior as of following:
1) Uses the AO specified in the AO field if its a valid channel
2) If its not a valid channel, falls back to the channel_id that the message is posted in.

I'll leave the MR open for a few days for feedback, and probably merge and deploy it later next week unless there are any objections.
