### ISSUE TITLE
Get backblasts from channels bot is a member of

### ISSUE THREAD

**Issue by taterhead247** [F3Nation-Community/PAXminer#9]
I put this out here knowing the effort to make it happen would be extensive.

The aos SQL table is populated using `slack.conversations_list(limit=999)` in F3SlackChannelLister.py. What if, instead, we used `slack.users_conversations(limit=999, types="private_channel,public_channel", exclude_archived=true)` (https://api.slack.com/methods/users.conversations). It works with the current permission set, gets both private and public, and trims down the list in the ao table.

In the aos table, instead of managing the archived channel and letting users control the backblast channel, you say that any channel PM is a member of will be checked for backblasts. This way users only have to do 1 thing (add bot to channel) instead of 2 things (add bot to channel and modify aos table). You would still want a boolean field in the aos table for "active" or something. By default, it's 1. If on a subsequent run, it doesn't see that channel anymore, it would set it to 0.

**Comment by srschaecher** [comment]
This is a good idea... feel free to create a pull request to update PAX_BD_Miner.py and F3SlackChannelLister.py if you have time. Otherwise I'll put this on my to-do list to work on.

**Comment by farrellw** [comment]
I think what complicates this request is Slackblast is another data collection tool that uses that AO table. So there are many use cases, I'd guess 35% of posts, that do not add Paxminer to a workspace or channel but do use the AO from their slack instance. 

So I think this idea is good @taterhead247 , but doesn't quite make sense in the current architecture until Slackblast and Paxminer merge into one app. Closing this issue due to that constraint, but if you think differently feel free to ping and can re-open for discussion.

**Comment by taterhead247** [comment]
Oh yeah. I agree with closing this. That may have made sense a year ago, but not today!
